update offline_eval_map_corloc.py
in config_util.get_configs_from_multiple_files, the key of the dict seems to be eval_input_configs instead of eval_input_config.
found that while following the Inference and evaluation on the Open Images dataset tutorial.
I was getting the error :
input_config = configs['eval_input_config']
KeyError: 'eval_input_config'