Replace deprecated git_repository rule
The native git_repository rule has been deprecated. Use the Skylark version available via load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository") instead.
Using native method gives error:
ERROR: Skipping 'single_task:run.par': error loading package 'single_task': Encountered error while reading extension file 'subpar.bzl': no such package '@subpar//': The native git_repository rule is deprecated. load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository") for a replacement.
Use --incompatible_remove_native_git_repository=false to temporarily continue using the native rule.
Source: